# Nome do Microserviço
spring.application.name=ms-notificador

# Configuração coringa do Host (aceita Docker ou Local)
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}

# Ativa o mecanismo de tentativas de conexão no BOOT da aplicação
spring.rabbitmq.template.retry.enabled=true
spring.rabbitmq.template.retry.initial-interval=3000ms
spring.rabbitmq.template.retry.max-attempts=6
spring.rabbitmq.template.retry.multiplier=1.5

# Conexão com o Servidor do RabbitMQ
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Ativa o mecanismo de tentativas automáticas do Spring AMQP
spring.rabbitmq.listener.simple.retry.enabled=true

# Número máximo de tentativas de entrega (1 original + 2 reprocessamentos)
spring.rabbitmq.listener.simple.retry.max-attempts=3

# Tempo de espera inicial entre cada tentativa (1000ms = 1 segundo)
spring.rabbitmq.listener.simple.retry.initial-interval=1000ms

# Multiplicador do intervalo (1.0 mantém o tempo fixo em 1 segundo por tentativa)
spring.rabbitmq.listener.simple.retry.multiplier=1.0

# FORÇA O RETRY MESMO PARA EXCEÇÕES GENÉRICAS DO JAVA
spring.rabbitmq.listener.simple.default-requeue-rejected=false

# Força o Spring a tentar se conectar ao RabbitMQ novamente se ele falhar no boot
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=5
spring.rabbitmq.listener.simple.retry.initial-interval=3000ms