# Nome do Microserviço
spring.application.name=ms-notificador

# Conexão com o Servidor do RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Ativa o mecanismo de tentativas automáticas do Spring AMQP
spring.rabbitmq.listener.simple.retry.enabled=true

# Número máximo de tentativas de entrega (1 original + 2 reprocessamentos)
spring.rabbitmq.listener.simple.retry.max-attempts=3

# Tempo de espera inicial entre cada tentativa (1000ms = 1 segundo)
spring.rabbitmq.listener.simple.retry.initial-interval=1000ms

# Multiplicador do intervalo (1.0 mantém o tempo fixo em 1 segundo por tentativa)
spring.rabbitmq.listener.simple.retry.multiplier=1.0

# FORÇA O RETRY MESMO PARA EXCEÇÕES GENÉRICAS DO JAVA
spring.rabbitmq.listener.simple.default-requeue-rejected=false