services:
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-container
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db_cadastro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db_cadastro"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4.0-management-alpine
    container_name: rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=ChaveSecretaDoGabriel123
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 5

  api-cadastro:
    build:
      context: ./api-cadastro
      dockerfile: Dockerfile
    container_name: api-cadastro-container
    ports:
      - "8080:8080"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/db_cadastro
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres-db:
        condition: service_healthy

  ms-notificador:
    build:
      context: ./MS-NOTIFICADOR/ms-notificador
      dockerfile: Dockerfile
    container_name: ms-notificador-container
    ports:
      - "8081:8081"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy