# Nome do Microserviço
spring.application.name=api-cadastro

# Conexão com o PostgreSQL das Notificações (Porta 5433)
spring.datasource.url=jdbc:postgresql://localhost:5433/db_cadastro
spring.datasource.username=gabriel
spring.datasource.password=adminpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Conexão com o Servidor do RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest